on:
  push:
    branch:
      - latest
  release:
name: ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: phpdoc/phar-ga
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
